wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 80
latent_dim:
  value: 20
learning_rate:
  value: 0.06485180494462059
log2_batch_size:
  value: 3
n_epochs:
  value: 17683177
seed:
  value: 123
x_dim:
  value: 784
