wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 905
latent_dim:
  value: 20
learning_rate:
  value: 0.06272938855317477
log2_batch_size:
  value: 2
n_epochs:
  value: 862981
seed:
  value: 123
x_dim:
  value: 784
