wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 180
latent_dim:
  value: 20
learning_rate:
  value: 0.023552626885031843
log2_batch_size:
  value: 3
n_epochs:
  value: 2208949
seed:
  value: 123
x_dim:
  value: 784
