wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 266
latent_dim:
  value: 20
learning_rate:
  value: 0.03179944481539427
log2_batch_size:
  value: 7
n_epochs:
  value: 5327170
seed:
  value: 123
x_dim:
  value: 784
