wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 1019
latent_dim:
  value: 20
learning_rate:
  value: 0.09072492819806977
log2_batch_size:
  value: 6
n_epochs:
  value: 309
seed:
  value: 123
x_dim:
  value: 784
