wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 856
latent_dim:
  value: 20
learning_rate:
  value: 0.027591233109254484
log2_batch_size:
  value: 2
n_epochs:
  value: 88176982
seed:
  value: 123
x_dim:
  value: 784
