wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 864
latent_dim:
  value: 20
learning_rate:
  value: 0.024955488199477353
log2_batch_size:
  value: 2
n_epochs:
  value: 47457
seed:
  value: 123
x_dim:
  value: 784
