wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 508
latent_dim:
  value: 20
learning_rate:
  value: 0.07724896470413223
log2_batch_size:
  value: 4
n_epochs:
  value: 7189
seed:
  value: 123
x_dim:
  value: 784
