wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 843
latent_dim:
  value: 20
learning_rate:
  value: 0.028322586880489116
log2_batch_size:
  value: 3
n_epochs:
  value: 165
seed:
  value: 123
x_dim:
  value: 784
