wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 400
latent_dim:
  value: 20
learning_rate:
  value: 0.09023110277414507
log2_batch_size:
  value: 2
n_epochs:
  value: 15
seed:
  value: 123
x_dim:
  value: 784
