wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 400
latent_dim:
  value: 20
learning_rate:
  value: 0.05057976354278124
log2_batch_size:
  value: 3
n_epochs:
  value: 18
seed:
  value: 123
x_dim:
  value: 784
