wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 712
latent_dim:
  value: 20
learning_rate:
  value: 0.045735559358349345
log2_batch_size:
  value: 4
n_epochs:
  value: 38447
seed:
  value: 123
x_dim:
  value: 784
