wandb_version: 1

dataset_path:
  value: ~/datasets
hidden_dim:
  value: 906
latent_dim:
  value: 20
learning_rate:
  value: 0.006758873897034587
log2_batch_size:
  value: 7
n_epochs:
  value: 52729
seed:
  value: 123
x_dim:
  value: 784
